### PR TITLE
Feat improved definition provider

### PR DESCRIPTION
**Pull request by HampB**
Once again, feel free to just close or redo the PR. There's probably better ways to get the task done. 

Made som updates to add additional features to the definitionProvider.
This includes require imports:
image
And also inline js functions:
image

Also made resolve behave the same way as ref, as far as i know there should be no issue with this.

### New Definition Providers:
* Added `DataformRequireDefinitionProvider` to handle definitions for `require` statements, enabling navigation to the required module's location.
* Added `DataformJsFunctionDefinitionProvider` to handle definitions for JavaScript functions imported via `require`, allowing users to navigate to the function's definition.

### Updates to Existing Providers:
* Enhanced `DataformRefDefinitionProvider` to support `${resolve}` syntax in addition to `${ref}`, improving the accuracy of definition lookups.

### Extension Activation:
* Updated the `activate` function to register the new `DataformRequireDefinitionProvider` and `DataformJsFunctionDefinitionProvider`, ensuring they are available when the extension is activated.
* Modified imports in `src/extension.ts` to include the new definition providers.

### CODE REVIEW

**Comment by ashish10alex** [comment]
Thanks for another PR ! 
I think I do not understand for which js blocks this go to ref is applicable for e.g. I was not able to make it work for the following 

---

[Link to the repo](https://github.com/ashish10alex/dataform-testing) where I am testing

---

CleanShot 2024-11-10 at 15 09 35@2x

**Comment by HampB** [comment]
I see, it's used without an require statement. My bad, i did not think that was possible anymore.
I've based the definition for inline js scripts on that the file contains a js block like this:
```
js {
    const query_label = require("includes/functions/query_label.js");
    const utils = require("includes/functions/utils.js");
}
```

I'll drop the JS part from the PR and come back at a later time with a better solution.

**Comment by HampB** [comment]
Updated PR to now only add definitions to:
```
require("my_file.js")
resolve("my_table")
```

**Comment by ashish10alex** [comment]
thank you ! works as described. In the future it would be cool if we could hover our the variable and it shows the value of the variable its its string/number/date. 

--

On a side note, I have had some issue with publishing a newer version of the extension. I initially got an error message when I ran `❯ vsce publish 0.2.28` from my terminal which is how I usually publish a newer version. 

```html
                <h2>Sorry! Our services aren't available right now.</h2>
                <p>We're working to restore all services as quickly as possible. Please check back soon.</p>

```

then when I tried again after few minutes I went through but I got the following email. Letting you know incase you wonder if why the release has not happened yet.

CleanShot 2024-11-10 at 17 32 45@2x

**Pull request merged**
